server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:${frontend_absolute_path}
  datasource:
    url: jdbc:h2:file:${application_h2_db_path};DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: h2_user
    password: h2_password
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: ${ddl_auto}
  h2:
    console:
      enabled: true
