server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:${frontend_absolute_path}
  datasource:
    url: jdbc:h2:file:${application_h2_db_path}
    driverClassName: org.h2.Driver
    username: h2_user
    password: h2_password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
doit:
  data:
    path: ${doit_data_path}
